# -*- coding: utf-8 -*-
"""util.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h5KhgUVuZC_UzXHJbRHHUIt0DkX0K73q
"""

import os; os.chdir('/content/drive/My Drive/Colab Notebooks/Lazy courses/Unsupervised Learning')

import numpy as np
import pandas as pd
from sklearn.utils import shuffle

def relu(x):
    return x * (x>0)

def error_rate(p, t):
    return np.mean(p != t)

def getKaggleMNIST():
    train = pd.read_csv('mnist_train.csv').values.astype(np.float32)
    train = shuffle(train)

    Xtrain = train[:-1000, 1:] /255
    Ytrain = train[:-1000, 0]
    Xtest = train[-1000:, 1:] /255
    Ytest = train[-1000:, 0]

    return Xtrain, Ytrain, Xtest, Ytest

def init_weights(shape):
    w = np.random.randn(*shape) / np.sqrt(sum(shape))
    return w.astype(np.float32)













